ACCOUNTS = [
  "GBL27HDAR7QOPYDOVGLYF3JG5WZ2IKX2633GRFGW43JTVBAPZM6KO5IG"
]

[DOCUMENTATION]
ORG_NAME="MARSM"
ORG_URL="https://qfsfoundation.github.io"
ORG_DESCRIPTION="MarsM is a visionary project developed on the Stellar network — focused on extracting and tokenizing."

ORG_LOGO="https://qfsfoundation.github.io/marsm/marsm.png"

[[CURRENCIES]]
code="MARSM"
name="MARSM"
status="live"
display_decimals=2
issuer="GBL27HDAR7QOPYDOVGLYF3JG5WZ2IKX2633GRFGW43JTVBAPZM6KO5IG"
anchor_asset_type="crypto"
desc="MarsM is a visionary project developed on the Stellar network — focused on extracting and tokenizing."
image="https://qfsfoundation.github.io/marsm/marsm.png"
